language: go
sudo: false

go:
  - 1.5
  - tip

install:
  - go get -t golang.org/x/net/context
  - go get -t golang.org/x/oauth2
  - go get -t golang.org/x/oauth2/jwt
  - go get -t google.golang.org/api/googleapi

script:
  - go test -v
